version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
  test:
    docker:
       - image: circleci/node:4.8.2
    steps:
      - run:
          name: Install npm
          command: npm test wdio.conf.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
