version: 2
jobs:
  test:
    docker:
       - image: circleci/node:10.16.0-chrome
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: test
          command: npm test wdio.conf.js
workflows:
  version: 2
  test:
    jobs:
      - test
